GLOBAL NEW_NAME IS "SatPolar1".
GLOBAL ORBIT_AP IS 400000.
GLOBAL ORBIT_PE IS 80000.
GLOBAL ORBIT_LAN IS -1.
GLOBAL ORBIT_INC IS 83.
GLOBAL ORBIT_W IS -1.
GLOBAL ORBIT_DIR IS -1.

GLOBAL STEER_SUN IS FALSE.
GLOBAL ORBIT_CIRK IS TRUE.
GLOBAL SHIP_ORBIT_SLOW IS TRUE.
GLOBAL SHIP_MAXQ_THR IS TRUE.
GLOBAL SHIP_TWR IS 2.0.
GLOBAL SHIP_THR_CONTROL IS TRUE.
GLOBAL SHIP_WARP_ALLOW IS FALSE.
GLOBAL ORBIT_LOW IS ORBIT_PE.
GLOBAL ANG_PREC IS 0.2.
GLOBAL ALT_PREC IS 1.0.
rcsOn().