GLOBAL NEW_NAME IS "Resc0".
GLOBAL ORBIT_LOW IS MAX(BODY:ATM:HEIGHT * 1.05, 74000).
GLOBAL BURN_WARP_CLOSE IS 30.
GLOBAL STEER_SUN IS TRUE.
GLOBAL ORBIT_CIRK IS TRUE.
GLOBAL SHIP_ORBIT_SLOW IS FALSE.
GLOBAL SHIP_MAXQ_THR IS TRUE.
GLOBAL SHIP_TWR IS 2.0.
GLOBAL SHIP_THR_CONTROL IS TRUE.
GLOBAL SHIP_WARP_ALLOW IS TRUE.
GLOBAL ORBIT_LOW IS 100000.
GLOBAL ANG_PREC IS 0.002.
GLOBAL ALT_PREC IS 0.010.
