GLOBAL ORBIT_BODY IS Minmus.
GLOBAL NEW_NAME IS "Zond1".
GLOBAL ORBIT_AP IS 400000.
GLOBAL ORBIT_PE IS 400000.
GLOBAL ORBIT_LAN IS -1.
GLOBAL ORBIT_INC IS 60.
GLOBAL ORBIT_W IS -1.
GLOBAL ORBIT_DIR IS 1.

GLOBAL ORBIT_BODY_INC IS ORBIT_BODY:OBT:INCLINATION.
GLOBAL ORBIT_BODY_LAN IS ORBIT_BODY:OBT:LAN.

GLOBAL STEER_SUN IS TRUE.

GLOBAL SHIP_TWR IS 2.1.
GLOBAL SHIP_WARP_ALLOW IS FALSE.
GLOBAL ORBIT_LOW IS MAX(BODY:ATM:HEIGHT * 1.05, 8000).
GLOBAL ANG_PREC IS 0.2.
GLOBAL ALT_PREC IS 1.0.
